GET http://localhost:3000
###
GET http://localhost:3000/get-sig
###
GET http://localhost:3000/protected
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtc2ciOiJoaSBtb20iLCJpYXQiOjE2NTc4NzEwMTEsImV4cCI6MTY1ODQ3NTgxMX0.pPE-Q6B7sMGgzLzRsklGpoEnTx3m8yAJY6aAqaCM2WY