apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: node-boilderplate
    labels:
        app: node-boilderplate
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: buildablekc0b119-buildablekc0-13ef.6857f2b11c5a4bfbb931.eastus.aksapp.io
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: node-boilderplate
                  port:
                    number: 3000