apiVersion: v1
kind: Service
metadata:
    name: node-boilderplate
    labels:
        app: node-boilderplate
spec:
    type: ClusterIP
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: node-boilderplate