apiVersion : apps/v1
kind: Deployment
metadata:
  name: node-boilderplate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-boilderplate
  template:
    metadata:
      labels:
        app: node-boilderplate
    spec:
      containers:
        - name: node-boilderplate
          image: "buildablecr0.azurecr.io/node-boilerplate"
          ports:
          - containerPort: 3000
          env:
          - name: secret
            valueFrom:
              secretKeyRef:
                name: mysecrets
                key: secret.txt