apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: node-boilderplate-ingress
    labels:
        app: node-boilderplate
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/issuer: letsencrypt
spec:
    rules:
        - host: buildablekc0-dns-b5a7f158.hcp.eastus.azmk8s.io
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: node-boilderplate
                  port:
                    number: 3000
    tls:
    - hosts:
      - buildablekc0-dns-b5a7f158.hcp.eastus.azmk8s.io
      secretName: tls-secret