GET http://localhost:3000
###
GET http://localhost:3000/get-sig
###
GET http://localhost:3000/protected
###
GET https://node-boiler.teaguestockwell.com
###
GET https://node-boiler.teaguestockwell.com/get-sig
###
GET https://node-boiler.teaguestockwell.com/protected
Authorization: 