on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: buildablecr0.azurecr.io
        username: ${{ secrets.acr_buildablecr0_username }}
        password: ${{ secrets.acr_buildablecr0_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t buildablecr0.azurecr.io/buildablekc0:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push buildablecr0.azurecr.io/buildablekc0:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_buildablekc0_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep buildablekc0b119 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace buildablekc0b119`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: buildablekc0b119
        container-registry-url: buildablecr0.azurecr.io
        container-registry-username: ${{ secrets.acr_buildablecr0_username }}
        container-registry-password: ${{ secrets.acr_buildablecr0_password }}
        secret-name: buildablekc0dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: buildablekc0b119
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          buildablecr0.azurecr.io/buildablekc0:${{ github.sha }}
        imagepullsecrets: |
          buildablekc0dockerauth
