name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Lint, test, compile, build, containerize and deploy

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Compile
        run: yarn compile

      - name: Build
        run: yarn build

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build image and push to registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            docker build . -f dockerfile.ci -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-boilerplate:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-boilerplate:${{ github.sha }}
      
      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_buildablekc0_kubeConfig }}
        id: login
      
      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep buildablekc0b119 | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace buildablekc0b119`
          fi

      - uses: azure/k8s-create-secret@v1
        with:
          namespace: buildablekc0b119
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: buildablekc0dockerauth
        
      - uses: azure/k8s-deploy@v1.2
        with:
          namespace: buildablekc0b119
          manifests: manifests/
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/node-boilerplate:${{ github.sha }}
          imagepullsecrets: |
            buildablekc0dockerauth
